version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/examples/python-flask"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
